[project]
name = "ine-api-exploration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt>=1.2.0",
    "duckdb>=1.1.2",
    "marimo>=0.9.9",
    "polars>=1.9.0",
]
